export interface ChineseWord {
  id: string
  simplified: string
  pinyin: string
  meaning: string
  hsk: number
  pos: string
  example: string
  exPinyin: string
  exMeaning: string
}

// Complete HSK 1 (150 words) + top HSK 2 words = 210 entries
// Pinyin uses proper tone marks; pos = part of speech
export const HSK_WORDS: ChineseWord[] = [
  // ── HSK 1 ──────────────────────────────────────────────────────────────────
  { id:'zh_001', simplified:'爱', pinyin:'ài', meaning:'love', hsk:1, pos:'verb', example:'我爱你。', exPinyin:'Wǒ ài nǐ.', exMeaning:'I love you.' },
  { id:'zh_002', simplified:'八', pinyin:'bā', meaning:'eight', hsk:1, pos:'number', example:'我有八本书。', exPinyin:'Wǒ yǒu bā běn shū.', exMeaning:'I have eight books.' },
  { id:'zh_003', simplified:'爸爸', pinyin:'bàba', meaning:'father / dad', hsk:1, pos:'noun', example:'我爸爸是医生。', exPinyin:'Wǒ bàba shì yīshēng.', exMeaning:'My dad is a doctor.' },
  { id:'zh_004', simplified:'杯子', pinyin:'bēizi', meaning:'cup / glass', hsk:1, pos:'noun', example:'这个杯子很漂亮。', exPinyin:'Zhège bēizi hěn piàoliang.', exMeaning:'This cup is very pretty.' },
  { id:'zh_005', simplified:'北京', pinyin:'Běijīng', meaning:'Beijing', hsk:1, pos:'noun', example:'我在北京工作。', exPinyin:'Wǒ zài Běijīng gōngzuò.', exMeaning:'I work in Beijing.' },
  { id:'zh_006', simplified:'不', pinyin:'bù', meaning:'not / no', hsk:1, pos:'adverb', example:'我不喜欢咖啡。', exPinyin:'Wǒ bù xǐhuan kāfēi.', exMeaning:'I don\'t like coffee.' },
  { id:'zh_007', simplified:'不客气', pinyin:'bú kèqi', meaning:"you're welcome", hsk:1, pos:'phrase', example:'谢谢你！不客气。', exPinyin:'Xièxie nǐ! Bú kèqi.', exMeaning:'Thank you! You\'re welcome.' },
  { id:'zh_008', simplified:'菜', pinyin:'cài', meaning:'dish / vegetable', hsk:1, pos:'noun', example:'这道菜很好吃。', exPinyin:'Zhè dào cài hěn hǎochī.', exMeaning:'This dish is delicious.' },
  { id:'zh_009', simplified:'茶', pinyin:'chá', meaning:'tea', hsk:1, pos:'noun', example:'我想喝茶。', exPinyin:'Wǒ xiǎng hē chá.', exMeaning:'I want to drink tea.' },
  { id:'zh_010', simplified:'吃', pinyin:'chī', meaning:'eat', hsk:1, pos:'verb', example:'你吃饭了吗？', exPinyin:'Nǐ chī fàn le ma?', exMeaning:'Have you eaten?' },
  { id:'zh_011', simplified:'出租车', pinyin:'chūzūchē', meaning:'taxi / cab', hsk:1, pos:'noun', example:'我坐出租车去。', exPinyin:'Wǒ zuò chūzūchē qù.', exMeaning:'I\'ll go by taxi.' },
  { id:'zh_012', simplified:'打电话', pinyin:'dǎ diànhuà', meaning:'make a phone call', hsk:1, pos:'phrase', example:'我给你打电话。', exPinyin:'Wǒ gěi nǐ dǎ diànhuà.', exMeaning:'I\'ll call you.' },
  { id:'zh_013', simplified:'大', pinyin:'dà', meaning:'big / large', hsk:1, pos:'adjective', example:'这个房子很大。', exPinyin:'Zhège fángzi hěn dà.', exMeaning:'This house is very big.' },
  { id:'zh_014', simplified:'的', pinyin:'de', meaning:'(possessive particle)', hsk:1, pos:'particle', example:'这是我的书。', exPinyin:'Zhè shì wǒ de shū.', exMeaning:'This is my book.' },
  { id:'zh_015', simplified:'点', pinyin:'diǎn', meaning:"o'clock / a little", hsk:1, pos:'measure', example:'现在三点。', exPinyin:'Xiànzài sān diǎn.', exMeaning:"It's three o'clock." },
  { id:'zh_016', simplified:'电脑', pinyin:'diànnǎo', meaning:'computer', hsk:1, pos:'noun', example:'我用电脑工作。', exPinyin:'Wǒ yòng diànnǎo gōngzuò.', exMeaning:'I use a computer for work.' },
  { id:'zh_017', simplified:'电视', pinyin:'diànshì', meaning:'television / TV', hsk:1, pos:'noun', example:'他在看电视。', exPinyin:'Tā zài kàn diànshì.', exMeaning:'He is watching TV.' },
  { id:'zh_018', simplified:'电影', pinyin:'diànyǐng', meaning:'movie / film', hsk:1, pos:'noun', example:'你喜欢看电影吗？', exPinyin:'Nǐ xǐhuan kàn diànyǐng ma?', exMeaning:'Do you like watching movies?' },
  { id:'zh_019', simplified:'东西', pinyin:'dōngxi', meaning:'thing / stuff', hsk:1, pos:'noun', example:'这是什么东西？', exPinyin:'Zhè shì shénme dōngxi?', exMeaning:'What is this thing?' },
  { id:'zh_020', simplified:'都', pinyin:'dōu', meaning:'all / both', hsk:1, pos:'adverb', example:'我们都喜欢中国。', exPinyin:'Wǒmen dōu xǐhuan Zhōngguó.', exMeaning:'We all like China.' },
  { id:'zh_021', simplified:'读', pinyin:'dú', meaning:'read (aloud)', hsk:1, pos:'verb', example:'请大声读。', exPinyin:'Qǐng dàshēng dú.', exMeaning:'Please read aloud.' },
  { id:'zh_022', simplified:'对不起', pinyin:'duìbuqǐ', meaning:'sorry / excuse me', hsk:1, pos:'phrase', example:'对不起，我来晚了。', exPinyin:'Duìbuqǐ, wǒ lái wǎn le.', exMeaning:'Sorry, I came late.' },
  { id:'zh_023', simplified:'多', pinyin:'duō', meaning:'many / much', hsk:1, pos:'adjective', example:'这里人很多。', exPinyin:'Zhèlǐ rén hěn duō.', exMeaning:'There are many people here.' },
  { id:'zh_024', simplified:'多少', pinyin:'duōshao', meaning:'how many / how much', hsk:1, pos:'question', example:'这个多少钱？', exPinyin:'Zhège duōshao qián?', exMeaning:'How much does this cost?' },
  { id:'zh_025', simplified:'儿子', pinyin:'érzi', meaning:'son', hsk:1, pos:'noun', example:'他的儿子很聪明。', exPinyin:'Tā de érzi hěn cōngmíng.', exMeaning:'His son is very smart.' },
  { id:'zh_026', simplified:'二', pinyin:'èr', meaning:'two', hsk:1, pos:'number', example:'我有两个儿子。', exPinyin:'Wǒ yǒu liǎng gè érzi.', exMeaning:'I have two sons.' },
  { id:'zh_027', simplified:'饭馆', pinyin:'fànguǎn', meaning:'restaurant', hsk:1, pos:'noun', example:'这家饭馆很有名。', exPinyin:'Zhè jiā fànguǎn hěn yǒumíng.', exMeaning:'This restaurant is famous.' },
  { id:'zh_028', simplified:'飞机', pinyin:'fēijī', meaning:'airplane', hsk:1, pos:'noun', example:'飞机几点起飞？', exPinyin:'Fēijī jǐ diǎn qǐfēi?', exMeaning:'What time does the plane take off?' },
  { id:'zh_029', simplified:'分钟', pinyin:'fēnzhōng', meaning:'minute', hsk:1, pos:'measure', example:'等我五分钟。', exPinyin:'Děng wǒ wǔ fēnzhōng.', exMeaning:'Wait five minutes for me.' },
  { id:'zh_030', simplified:'高兴', pinyin:'gāoxìng', meaning:'happy / glad', hsk:1, pos:'adjective', example:'我很高兴见到你。', exPinyin:'Wǒ hěn gāoxìng jiàndào nǐ.', exMeaning:'I\'m happy to meet you.' },
  { id:'zh_031', simplified:'个', pinyin:'gè', meaning:'(general measure word)', hsk:1, pos:'measure', example:'我有三个朋友。', exPinyin:'Wǒ yǒu sān gè péngyou.', exMeaning:'I have three friends.' },
  { id:'zh_032', simplified:'工作', pinyin:'gōngzuò', meaning:'work / job', hsk:1, pos:'noun/verb', example:'你在哪里工作？', exPinyin:'Nǐ zài nǎlǐ gōngzuò?', exMeaning:'Where do you work?' },
  { id:'zh_033', simplified:'狗', pinyin:'gǒu', meaning:'dog', hsk:1, pos:'noun', example:'我家有一只狗。', exPinyin:'Wǒ jiā yǒu yī zhī gǒu.', exMeaning:'My family has a dog.' },
  { id:'zh_034', simplified:'汉语', pinyin:'Hànyǔ', meaning:'Chinese language / Mandarin', hsk:1, pos:'noun', example:'我在学汉语。', exPinyin:'Wǒ zài xué Hànyǔ.', exMeaning:'I am learning Chinese.' },
  { id:'zh_035', simplified:'好', pinyin:'hǎo', meaning:'good / well', hsk:1, pos:'adjective', example:'你好！', exPinyin:'Nǐ hǎo!', exMeaning:'Hello!' },
  { id:'zh_036', simplified:'好吃', pinyin:'hǎochī', meaning:'delicious / tasty', hsk:1, pos:'adjective', example:'这个菜真好吃！', exPinyin:'Zhège cài zhēn hǎochī!', exMeaning:'This dish is really delicious!' },
  { id:'zh_037', simplified:'号', pinyin:'hào', meaning:'number / date', hsk:1, pos:'noun', example:'今天几号？', exPinyin:'Jīntiān jǐ hào?', exMeaning:'What date is today?' },
  { id:'zh_038', simplified:'喝', pinyin:'hē', meaning:'drink', hsk:1, pos:'verb', example:'你喝什么？', exPinyin:'Nǐ hē shénme?', exMeaning:'What are you drinking?' },
  { id:'zh_039', simplified:'和', pinyin:'hé', meaning:'and / with', hsk:1, pos:'conjunction', example:'我和你一起去。', exPinyin:'Wǒ hé nǐ yīqǐ qù.', exMeaning:'I\'ll go together with you.' },
  { id:'zh_040', simplified:'很', pinyin:'hěn', meaning:'very', hsk:1, pos:'adverb', example:'他很高。', exPinyin:'Tā hěn gāo.', exMeaning:'He is very tall.' },
  { id:'zh_041', simplified:'后面', pinyin:'hòumiàn', meaning:'behind / at the back', hsk:1, pos:'noun', example:'学校后面有公园。', exPinyin:'Xuéxiào hòumiàn yǒu gōngyuán.', exMeaning:'There is a park behind the school.' },
  { id:'zh_042', simplified:'回', pinyin:'huí', meaning:'return / go back', hsk:1, pos:'verb', example:'我明天回家。', exPinyin:'Wǒ míngtiān huí jiā.', exMeaning:'I\'ll go home tomorrow.' },
  { id:'zh_043', simplified:'会', pinyin:'huì', meaning:'can / know how to', hsk:1, pos:'modal', example:'你会说汉语吗？', exPinyin:'Nǐ huì shuō Hànyǔ ma?', exMeaning:'Can you speak Chinese?' },
  { id:'zh_044', simplified:'几', pinyin:'jǐ', meaning:'how many (small number)', hsk:1, pos:'question', example:'你家有几口人？', exPinyin:'Nǐ jiā yǒu jǐ kǒu rén?', exMeaning:'How many people are in your family?' },
  { id:'zh_045', simplified:'家', pinyin:'jiā', meaning:'home / family', hsk:1, pos:'noun', example:'我的家在北京。', exPinyin:'Wǒ de jiā zài Běijīng.', exMeaning:'My home is in Beijing.' },
  { id:'zh_046', simplified:'叫', pinyin:'jiào', meaning:'be called / call', hsk:1, pos:'verb', example:'你叫什么名字？', exPinyin:'Nǐ jiào shénme míngzi?', exMeaning:'What is your name?' },
  { id:'zh_047', simplified:'今天', pinyin:'jīntiān', meaning:'today', hsk:1, pos:'time', example:'今天天气很好。', exPinyin:'Jīntiān tiānqì hěn hǎo.', exMeaning:'The weather is nice today.' },
  { id:'zh_048', simplified:'九', pinyin:'jiǔ', meaning:'nine', hsk:1, pos:'number', example:'九月份很凉快。', exPinyin:'Jiǔ yuèfèn hěn liángkuai.', exMeaning:'September is very cool.' },
  { id:'zh_049', simplified:'开', pinyin:'kāi', meaning:'open / drive / turn on', hsk:1, pos:'verb', example:'请把门开开。', exPinyin:'Qǐng bǎ mén kāi kāi.', exMeaning:'Please open the door.' },
  { id:'zh_050', simplified:'看', pinyin:'kàn', meaning:'look / watch / read', hsk:1, pos:'verb', example:'我在看书。', exPinyin:'Wǒ zài kàn shū.', exMeaning:'I am reading a book.' },
  { id:'zh_051', simplified:'看见', pinyin:'kànjiàn', meaning:'see / catch sight of', hsk:1, pos:'verb', example:'你看见他了吗？', exPinyin:'Nǐ kànjiàn tā le ma?', exMeaning:'Did you see him?' },
  { id:'zh_052', simplified:'块', pinyin:'kuài', meaning:'yuan / piece', hsk:1, pos:'measure', example:'苹果一块钱一个。', exPinyin:'Píngguǒ yī kuài qián yī gè.', exMeaning:'Apples are one yuan each.' },
  { id:'zh_053', simplified:'来', pinyin:'lái', meaning:'come', hsk:1, pos:'verb', example:'你来这里工作吗？', exPinyin:'Nǐ lái zhèlǐ gōngzuò ma?', exMeaning:'Did you come here to work?' },
  { id:'zh_054', simplified:'老师', pinyin:'lǎoshī', meaning:'teacher', hsk:1, pos:'noun', example:'她是我们的英语老师。', exPinyin:'Tā shì wǒmen de Yīngyǔ lǎoshī.', exMeaning:'She is our English teacher.' },
  { id:'zh_055', simplified:'冷', pinyin:'lěng', meaning:'cold', hsk:1, pos:'adjective', example:'今天很冷。', exPinyin:'Jīntiān hěn lěng.', exMeaning:'It\'s very cold today.' },
  { id:'zh_056', simplified:'里', pinyin:'lǐ', meaning:'inside / in', hsk:1, pos:'noun', example:'书包里有什么？', exPinyin:'Shūbāo lǐ yǒu shénme?', exMeaning:'What is inside the backpack?' },
  { id:'zh_057', simplified:'六', pinyin:'liù', meaning:'six', hsk:1, pos:'number', example:'我们班有六个学生。', exPinyin:'Wǒmen bān yǒu liù gè xuésheng.', exMeaning:'Our class has six students.' },
  { id:'zh_058', simplified:'妈妈', pinyin:'māma', meaning:'mother / mom', hsk:1, pos:'noun', example:'我妈妈在家。', exPinyin:'Wǒ māma zài jiā.', exMeaning:'My mom is at home.' },
  { id:'zh_059', simplified:'吗', pinyin:'ma', meaning:'(yes/no question particle)', hsk:1, pos:'particle', example:'你是学生吗？', exPinyin:'Nǐ shì xuésheng ma?', exMeaning:'Are you a student?' },
  { id:'zh_060', simplified:'买', pinyin:'mǎi', meaning:'buy', hsk:1, pos:'verb', example:'我想买一件衣服。', exPinyin:'Wǒ xiǎng mǎi yī jiàn yīfu.', exMeaning:'I want to buy a piece of clothing.' },
  { id:'zh_061', simplified:'猫', pinyin:'māo', meaning:'cat', hsk:1, pos:'noun', example:'这只猫很可爱。', exPinyin:'Zhè zhī māo hěn kě\'ài.', exMeaning:'This cat is very cute.' },
  { id:'zh_062', simplified:'没有', pinyin:'méiyǒu', meaning:"don't have / there isn't", hsk:1, pos:'verb', example:'我没有钱。', exPinyin:'Wǒ méiyǒu qián.', exMeaning:'I don\'t have money.' },
  { id:'zh_063', simplified:'没关系', pinyin:'méi guānxi', meaning:"never mind / that's OK", hsk:1, pos:'phrase', example:'对不起！没关系。', exPinyin:'Duìbuqǐ! Méi guānxi.', exMeaning:'Sorry! Never mind.' },
  { id:'zh_064', simplified:'米饭', pinyin:'mǐfàn', meaning:'(cooked) rice', hsk:1, pos:'noun', example:'我喜欢吃米饭。', exPinyin:'Wǒ xǐhuan chī mǐfàn.', exMeaning:'I like eating rice.' },
  { id:'zh_065', simplified:'名字', pinyin:'míngzi', meaning:'name', hsk:1, pos:'noun', example:'你的名字是什么？', exPinyin:'Nǐ de míngzi shì shénme?', exMeaning:'What is your name?' },
  { id:'zh_066', simplified:'明天', pinyin:'míngtiān', meaning:'tomorrow', hsk:1, pos:'time', example:'明天见！', exPinyin:'Míngtiān jiàn!', exMeaning:'See you tomorrow!' },
  { id:'zh_067', simplified:'哪', pinyin:'nǎ', meaning:'which / where', hsk:1, pos:'question', example:'你是哪国人？', exPinyin:'Nǐ shì nǎ guó rén?', exMeaning:'Which country are you from?' },
  { id:'zh_068', simplified:'那', pinyin:'nà', meaning:'that', hsk:1, pos:'pronoun', example:'那是什么？', exPinyin:'Nà shì shénme?', exMeaning:'What is that?' },
  { id:'zh_069', simplified:'能', pinyin:'néng', meaning:'can / be able to', hsk:1, pos:'modal', example:'你能帮我吗？', exPinyin:'Nǐ néng bāng wǒ ma?', exMeaning:'Can you help me?' },
  { id:'zh_070', simplified:'你', pinyin:'nǐ', meaning:'you (singular)', hsk:1, pos:'pronoun', example:'你好！', exPinyin:'Nǐ hǎo!', exMeaning:'Hello!' },
  { id:'zh_071', simplified:'你好', pinyin:'nǐ hǎo', meaning:'hello / hi', hsk:1, pos:'phrase', example:'你好，我叫李明。', exPinyin:'Nǐ hǎo, wǒ jiào Lǐ Míng.', exMeaning:'Hello, my name is Li Ming.' },
  { id:'zh_072', simplified:'年', pinyin:'nián', meaning:'year', hsk:1, pos:'noun', example:'今年是哪年？', exPinyin:'Jīnnián shì nǎ nián?', exMeaning:'What year is this year?' },
  { id:'zh_073', simplified:'女儿', pinyin:'nǚér', meaning:'daughter', hsk:1, pos:'noun', example:'她的女儿很可爱。', exPinyin:'Tā de nǚér hěn kě\'ài.', exMeaning:'Her daughter is very cute.' },
  { id:'zh_074', simplified:'朋友', pinyin:'péngyou', meaning:'friend', hsk:1, pos:'noun', example:'他是我的好朋友。', exPinyin:'Tā shì wǒ de hǎo péngyou.', exMeaning:'He is my good friend.' },
  { id:'zh_075', simplified:'漂亮', pinyin:'piàoliang', meaning:'pretty / beautiful', hsk:1, pos:'adjective', example:'她穿的衣服很漂亮。', exPinyin:'Tā chuān de yīfu hěn piàoliang.', exMeaning:'The clothes she wears are very pretty.' },
  { id:'zh_076', simplified:'苹果', pinyin:'píngguǒ', meaning:'apple', hsk:1, pos:'noun', example:'我喜欢吃苹果。', exPinyin:'Wǒ xǐhuan chī píngguǒ.', exMeaning:'I like eating apples.' },
  { id:'zh_077', simplified:'七', pinyin:'qī', meaning:'seven', hsk:1, pos:'number', example:'一周有七天。', exPinyin:'Yī zhōu yǒu qī tiān.', exMeaning:'There are seven days in a week.' },
  { id:'zh_078', simplified:'钱', pinyin:'qián', meaning:'money', hsk:1, pos:'noun', example:'你有多少钱？', exPinyin:'Nǐ yǒu duōshao qián?', exMeaning:'How much money do you have?' },
  { id:'zh_079', simplified:'前面', pinyin:'qiánmiàn', meaning:'in front / ahead', hsk:1, pos:'noun', example:'学校前面有一家商店。', exPinyin:'Xuéxiào qiánmiàn yǒu yī jiā shāngdiàn.', exMeaning:'There is a store in front of the school.' },
  { id:'zh_080', simplified:'去', pinyin:'qù', meaning:'go', hsk:1, pos:'verb', example:'我去学校。', exPinyin:'Wǒ qù xuéxiào.', exMeaning:'I\'m going to school.' },
  { id:'zh_081', simplified:'热', pinyin:'rè', meaning:'hot', hsk:1, pos:'adjective', example:'今天天气很热。', exPinyin:'Jīntiān tiānqì hěn rè.', exMeaning:'The weather is very hot today.' },
  { id:'zh_082', simplified:'人', pinyin:'rén', meaning:'person / people', hsk:1, pos:'noun', example:'他是一个好人。', exPinyin:'Tā shì yī gè hǎo rén.', exMeaning:'He is a good person.' },
  { id:'zh_083', simplified:'认识', pinyin:'rènshi', meaning:'know (a person)', hsk:1, pos:'verb', example:'我认识他。', exPinyin:'Wǒ rènshi tā.', exMeaning:'I know him.' },
  { id:'zh_084', simplified:'三', pinyin:'sān', meaning:'three', hsk:1, pos:'number', example:'我有三个姐姐。', exPinyin:'Wǒ yǒu sān gè jiějie.', exMeaning:'I have three older sisters.' },
  { id:'zh_085', simplified:'商店', pinyin:'shāngdiàn', meaning:'store / shop', hsk:1, pos:'noun', example:'这家商店卖什么？', exPinyin:'Zhè jiā shāngdiàn mài shénme?', exMeaning:'What does this store sell?' },
  { id:'zh_086', simplified:'上午', pinyin:'shàngwǔ', meaning:'morning (before noon)', hsk:1, pos:'time', example:'我上午九点上班。', exPinyin:'Wǒ shàngwǔ jiǔ diǎn shàngbān.', exMeaning:'I start work at 9 AM.' },
  { id:'zh_087', simplified:'少', pinyin:'shǎo', meaning:'few / little', hsk:1, pos:'adjective', example:'这里人很少。', exPinyin:'Zhèlǐ rén hěn shǎo.', exMeaning:'There are few people here.' },
  { id:'zh_088', simplified:'谁', pinyin:'shéi', meaning:'who', hsk:1, pos:'question', example:'那个人是谁？', exPinyin:'Nàge rén shì shéi?', exMeaning:'Who is that person?' },
  { id:'zh_089', simplified:'什么', pinyin:'shénme', meaning:'what', hsk:1, pos:'question', example:'你想吃什么？', exPinyin:'Nǐ xiǎng chī shénme?', exMeaning:'What do you want to eat?' },
  { id:'zh_090', simplified:'时候', pinyin:'shíhou', meaning:'time / moment / when', hsk:1, pos:'noun', example:'你什么时候来？', exPinyin:'Nǐ shénme shíhou lái?', exMeaning:'When are you coming?' },
  { id:'zh_091', simplified:'是', pinyin:'shì', meaning:'be (am / is / are)', hsk:1, pos:'verb', example:'我是学生。', exPinyin:'Wǒ shì xuésheng.', exMeaning:'I am a student.' },
  { id:'zh_092', simplified:'书', pinyin:'shū', meaning:'book', hsk:1, pos:'noun', example:'这本书很有意思。', exPinyin:'Zhè běn shū hěn yǒu yìsi.', exMeaning:'This book is very interesting.' },
  { id:'zh_093', simplified:'水', pinyin:'shuǐ', meaning:'water', hsk:1, pos:'noun', example:'我想喝水。', exPinyin:'Wǒ xiǎng hē shuǐ.', exMeaning:'I want to drink water.' },
  { id:'zh_094', simplified:'水果', pinyin:'shuǐguǒ', meaning:'fruit', hsk:1, pos:'noun', example:'你喜欢吃什么水果？', exPinyin:'Nǐ xǐhuan chī shénme shuǐguǒ?', exMeaning:'What fruit do you like?' },
  { id:'zh_095', simplified:'睡觉', pinyin:'shuì jiào', meaning:'sleep', hsk:1, pos:'verb', example:'我想睡觉了。', exPinyin:'Wǒ xiǎng shuì jiào le.', exMeaning:'I want to sleep.' },
  { id:'zh_096', simplified:'说', pinyin:'shuō', meaning:'speak / say / talk', hsk:1, pos:'verb', example:'他说汉语说得很好。', exPinyin:'Tā shuō Hànyǔ shuō de hěn hǎo.', exMeaning:'He speaks Chinese very well.' },
  { id:'zh_097', simplified:'四', pinyin:'sì', meaning:'four', hsk:1, pos:'number', example:'我今年四十岁。', exPinyin:'Wǒ jīnnián sìshí suì.', exMeaning:'I am forty years old this year.' },
  { id:'zh_098', simplified:'岁', pinyin:'suì', meaning:'years old', hsk:1, pos:'measure', example:'他五岁了。', exPinyin:'Tā wǔ suì le.', exMeaning:'He is five years old.' },
  { id:'zh_099', simplified:'他', pinyin:'tā', meaning:'he / him', hsk:1, pos:'pronoun', example:'他是我的同学。', exPinyin:'Tā shì wǒ de tóngxué.', exMeaning:'He is my classmate.' },
  { id:'zh_100', simplified:'她', pinyin:'tā', meaning:'she / her', hsk:1, pos:'pronoun', example:'她很漂亮。', exPinyin:'Tā hěn piàoliang.', exMeaning:'She is very pretty.' },
  { id:'zh_101', simplified:'太', pinyin:'tài', meaning:'too / so', hsk:1, pos:'adverb', example:'这个太贵了！', exPinyin:'Zhège tài guì le!', exMeaning:'This is too expensive!' },
  { id:'zh_102', simplified:'天气', pinyin:'tiānqì', meaning:'weather', hsk:1, pos:'noun', example:'今天天气怎么样？', exPinyin:'Jīntiān tiānqì zěnmeyàng?', exMeaning:'How is the weather today?' },
  { id:'zh_103', simplified:'听', pinyin:'tīng', meaning:'listen / hear', hsk:1, pos:'verb', example:'我喜欢听音乐。', exPinyin:'Wǒ xǐhuan tīng yīnyuè.', exMeaning:'I like listening to music.' },
  { id:'zh_104', simplified:'同学', pinyin:'tóngxué', meaning:'classmate', hsk:1, pos:'noun', example:'他是我的同学。', exPinyin:'Tā shì wǒ de tóngxué.', exMeaning:'He is my classmate.' },
  { id:'zh_105', simplified:'我', pinyin:'wǒ', meaning:'I / me', hsk:1, pos:'pronoun', example:'我是中国人。', exPinyin:'Wǒ shì Zhōngguó rén.', exMeaning:'I am Chinese.' },
  { id:'zh_106', simplified:'我们', pinyin:'wǒmen', meaning:'we / us', hsk:1, pos:'pronoun', example:'我们都是朋友。', exPinyin:'Wǒmen dōu shì péngyou.', exMeaning:'We are all friends.' },
  { id:'zh_107', simplified:'五', pinyin:'wǔ', meaning:'five', hsk:1, pos:'number', example:'我每天工作五个小时。', exPinyin:'Wǒ měitiān gōngzuò wǔ gè xiǎoshí.', exMeaning:'I work five hours every day.' },
  { id:'zh_108', simplified:'喜欢', pinyin:'xǐhuan', meaning:'like / enjoy', hsk:1, pos:'verb', example:'我喜欢学汉语。', exPinyin:'Wǒ xǐhuan xué Hànyǔ.', exMeaning:'I like learning Chinese.' },
  { id:'zh_109', simplified:'下午', pinyin:'xiàwǔ', meaning:'afternoon', hsk:1, pos:'time', example:'下午三点见。', exPinyin:'Xiàwǔ sān diǎn jiàn.', exMeaning:'See you at 3 PM.' },
  { id:'zh_110', simplified:'先生', pinyin:'xiānsheng', meaning:'Mr. / Sir / husband', hsk:1, pos:'noun', example:'王先生，您好！', exPinyin:'Wáng xiānsheng, nín hǎo!', exMeaning:'Good day, Mr. Wang!' },
  { id:'zh_111', simplified:'现在', pinyin:'xiànzài', meaning:'now / at present', hsk:1, pos:'time', example:'现在几点？', exPinyin:'Xiànzài jǐ diǎn?', exMeaning:'What time is it now?' },
  { id:'zh_112', simplified:'想', pinyin:'xiǎng', meaning:'want / think / miss', hsk:1, pos:'verb', example:'我想去中国。', exPinyin:'Wǒ xiǎng qù Zhōngguó.', exMeaning:'I want to go to China.' },
  { id:'zh_113', simplified:'小', pinyin:'xiǎo', meaning:'small / little', hsk:1, pos:'adjective', example:'这只猫很小。', exPinyin:'Zhè zhī māo hěn xiǎo.', exMeaning:'This cat is very small.' },
  { id:'zh_114', simplified:'写', pinyin:'xiě', meaning:'write', hsk:1, pos:'verb', example:'请写下你的名字。', exPinyin:'Qǐng xiě xià nǐ de míngzi.', exMeaning:'Please write down your name.' },
  { id:'zh_115', simplified:'谢谢', pinyin:'xièxie', meaning:'thank you', hsk:1, pos:'phrase', example:'谢谢你的帮助。', exPinyin:'Xièxie nǐ de bāngzhù.', exMeaning:'Thank you for your help.' },
  { id:'zh_116', simplified:'星期', pinyin:'xīngqī', meaning:'week', hsk:1, pos:'noun', example:'一星期有七天。', exPinyin:'Yī xīngqī yǒu qī tiān.', exMeaning:'There are seven days in a week.' },
  { id:'zh_117', simplified:'学生', pinyin:'xuésheng', meaning:'student', hsk:1, pos:'noun', example:'她是一年级的学生。', exPinyin:'Tā shì yī niánjí de xuésheng.', exMeaning:'She is a first-grade student.' },
  { id:'zh_118', simplified:'学习', pinyin:'xuéxí', meaning:'study / learn', hsk:1, pos:'verb', example:'我每天学习两个小时。', exPinyin:'Wǒ měitiān xuéxí liǎng gè xiǎoshí.', exMeaning:'I study two hours every day.' },
  { id:'zh_119', simplified:'学校', pinyin:'xuéxiào', meaning:'school', hsk:1, pos:'noun', example:'他们的学校很大。', exPinyin:'Tāmen de xuéxiào hěn dà.', exMeaning:'Their school is very big.' },
  { id:'zh_120', simplified:'一', pinyin:'yī', meaning:'one', hsk:1, pos:'number', example:'我只有一个苹果。', exPinyin:'Wǒ zhǐ yǒu yī gè píngguǒ.', exMeaning:'I only have one apple.' },
  { id:'zh_121', simplified:'衣服', pinyin:'yīfu', meaning:'clothes / clothing', hsk:1, pos:'noun', example:'这件衣服多少钱？', exPinyin:'Zhè jiàn yīfu duōshao qián?', exMeaning:'How much is this piece of clothing?' },
  { id:'zh_122', simplified:'医生', pinyin:'yīshēng', meaning:'doctor', hsk:1, pos:'noun', example:'医生让我休息。', exPinyin:'Yīshēng ràng wǒ xiūxi.', exMeaning:'The doctor told me to rest.' },
  { id:'zh_123', simplified:'医院', pinyin:'yīyuàn', meaning:'hospital', hsk:1, pos:'noun', example:'我去医院看病。', exPinyin:'Wǒ qù yīyuàn kànbìng.', exMeaning:'I go to the hospital to see a doctor.' },
  { id:'zh_124', simplified:'椅子', pinyin:'yǐzi', meaning:'chair', hsk:1, pos:'noun', example:'请坐这把椅子。', exPinyin:'Qǐng zuò zhè bǎ yǐzi.', exMeaning:'Please sit on this chair.' },
  { id:'zh_125', simplified:'也', pinyin:'yě', meaning:'also / too', hsk:1, pos:'adverb', example:'我也喜欢唱歌。', exPinyin:'Wǒ yě xǐhuan chànggē.', exMeaning:'I also like singing.' },
  { id:'zh_126', simplified:'有', pinyin:'yǒu', meaning:'have / there is', hsk:1, pos:'verb', example:'我有一个问题。', exPinyin:'Wǒ yǒu yī gè wèntí.', exMeaning:'I have a question.' },
  { id:'zh_127', simplified:'月', pinyin:'yuè', meaning:'month', hsk:1, pos:'noun', example:'三月份天气很好。', exPinyin:'Sān yuèfèn tiānqì hěn hǎo.', exMeaning:'March has great weather.' },
  { id:'zh_128', simplified:'在', pinyin:'zài', meaning:'at / in / be at', hsk:1, pos:'verb', example:'我在家。', exPinyin:'Wǒ zài jiā.', exMeaning:'I am at home.' },
  { id:'zh_129', simplified:'再见', pinyin:'zàijiàn', meaning:'goodbye / see you', hsk:1, pos:'phrase', example:'明天见！再见！', exPinyin:'Míngtiān jiàn! Zàijiàn!', exMeaning:'See you tomorrow! Goodbye!' },
  { id:'zh_130', simplified:'怎么', pinyin:'zěnme', meaning:'how / why', hsk:1, pos:'question', example:'你怎么去？', exPinyin:'Nǐ zěnme qù?', exMeaning:'How are you going?' },
  { id:'zh_131', simplified:'怎么样', pinyin:'zěnmeyàng', meaning:'how about / how is it', hsk:1, pos:'question', example:'你怎么样？', exPinyin:'Nǐ zěnmeyàng?', exMeaning:'How are you doing?' },
  { id:'zh_132', simplified:'这', pinyin:'zhè', meaning:'this', hsk:1, pos:'pronoun', example:'这是我的书。', exPinyin:'Zhè shì wǒ de shū.', exMeaning:'This is my book.' },
  { id:'zh_133', simplified:'中国', pinyin:'Zhōngguó', meaning:'China', hsk:1, pos:'noun', example:'我来自中国。', exPinyin:'Wǒ láizì Zhōngguó.', exMeaning:'I come from China.' },
  { id:'zh_134', simplified:'中午', pinyin:'zhōngwǔ', meaning:'noon / midday', hsk:1, pos:'time', example:'中午我去吃饭。', exPinyin:'Zhōngwǔ wǒ qù chīfàn.', exMeaning:'I go to eat at noon.' },
  { id:'zh_135', simplified:'住', pinyin:'zhù', meaning:'live / reside / stay', hsk:1, pos:'verb', example:'你住在哪里？', exPinyin:'Nǐ zhù zài nǎlǐ?', exMeaning:'Where do you live?' },
  { id:'zh_136', simplified:'桌子', pinyin:'zhuōzi', meaning:'table / desk', hsk:1, pos:'noun', example:'桌子上有一本书。', exPinyin:'Zhuōzi shàng yǒu yī běn shū.', exMeaning:'There is a book on the table.' },
  { id:'zh_137', simplified:'字', pinyin:'zì', meaning:'character / word', hsk:1, pos:'noun', example:'这个字怎么写？', exPinyin:'Zhège zì zěnme xiě?', exMeaning:'How do you write this character?' },
  { id:'zh_138', simplified:'昨天', pinyin:'zuótiān', meaning:'yesterday', hsk:1, pos:'time', example:'昨天我去了公园。', exPinyin:'Zuótiān wǒ qù le gōngyuán.', exMeaning:'Yesterday I went to the park.' },
  { id:'zh_139', simplified:'坐', pinyin:'zuò', meaning:'sit / travel by', hsk:1, pos:'verb', example:'请坐！', exPinyin:'Qǐng zuò!', exMeaning:'Please sit down!' },
  { id:'zh_140', simplified:'做', pinyin:'zuò', meaning:'do / make', hsk:1, pos:'verb', example:'你在做什么？', exPinyin:'Nǐ zài zuò shénme?', exMeaning:'What are you doing?' },
  { id:'zh_141', simplified:'零', pinyin:'líng', meaning:'zero', hsk:1, pos:'number', example:'今天零下五度。', exPinyin:'Jīntiān líng xià wǔ dù.', exMeaning:'It\'s minus five degrees today.' },
  { id:'zh_142', simplified:'喂', pinyin:'wèi', meaning:'hello (phone) / hey', hsk:1, pos:'interjection', example:'喂，你好！', exPinyin:'Wèi, nǐ hǎo!', exMeaning:'Hello! (on the phone)' },

  // ── HSK 2 ──────────────────────────────────────────────────────────────────
  { id:'zh_201', simplified:'白', pinyin:'bái', meaning:'white', hsk:2, pos:'adjective', example:'她穿着白色的裙子。', exPinyin:'Tā chuānzhe báisè de qúnzi.', exMeaning:'She is wearing a white skirt.' },
  { id:'zh_202', simplified:'帮助', pinyin:'bāngzhù', meaning:'help / assist', hsk:2, pos:'verb', example:'谢谢你帮助我。', exPinyin:'Xièxie nǐ bāngzhù wǒ.', exMeaning:'Thank you for helping me.' },
  { id:'zh_203', simplified:'比', pinyin:'bǐ', meaning:'compare / than', hsk:2, pos:'preposition', example:'他比我高。', exPinyin:'Tā bǐ wǒ gāo.', exMeaning:'He is taller than me.' },
  { id:'zh_204', simplified:'别', pinyin:'bié', meaning:"don't / other", hsk:2, pos:'adverb', example:'别担心！', exPinyin:'Bié dānxīn!', exMeaning:"Don't worry!" },
  { id:'zh_205', simplified:'长', pinyin:'cháng', meaning:'long', hsk:2, pos:'adjective', example:'这条路很长。', exPinyin:'Zhè tiáo lù hěn cháng.', exMeaning:'This road is very long.' },
  { id:'zh_206', simplified:'唱歌', pinyin:'chànggē', meaning:'sing (a song)', hsk:2, pos:'verb', example:'她喜欢唱歌。', exPinyin:'Tā xǐhuan chànggē.', exMeaning:'She likes to sing.' },
  { id:'zh_207', simplified:'穿', pinyin:'chuān', meaning:'wear / put on', hsk:2, pos:'verb', example:'今天我穿了一件新衣服。', exPinyin:'Jīntiān wǒ chuān le yī jiàn xīn yīfu.', exMeaning:'Today I wore a new piece of clothing.' },
  { id:'zh_208', simplified:'从', pinyin:'cóng', meaning:'from / since', hsk:2, pos:'preposition', example:'我从北京来。', exPinyin:'Wǒ cóng Běijīng lái.', exMeaning:'I come from Beijing.' },
  { id:'zh_209', simplified:'错', pinyin:'cuò', meaning:'wrong / mistake', hsk:2, pos:'adjective', example:'这个答案是错的。', exPinyin:'Zhège dá\'àn shì cuò de.', exMeaning:'This answer is wrong.' },
  { id:'zh_210', simplified:'但是', pinyin:'dànshì', meaning:'but / however', hsk:2, pos:'conjunction', example:'我想去，但是没有时间。', exPinyin:'Wǒ xiǎng qù, dànshì méiyǒu shíjiān.', exMeaning:'I want to go, but I don\'t have time.' },
  { id:'zh_211', simplified:'地铁', pinyin:'dìtiě', meaning:'subway / metro', hsk:2, pos:'noun', example:'我坐地铁上班。', exPinyin:'Wǒ zuò dìtiě shàngbān.', exMeaning:'I take the subway to work.' },
  { id:'zh_212', simplified:'弟弟', pinyin:'dìdi', meaning:'younger brother', hsk:2, pos:'noun', example:'我弟弟比我小三岁。', exPinyin:'Wǒ dìdi bǐ wǒ xiǎo sān suì.', exMeaning:'My younger brother is three years younger than me.' },
  { id:'zh_213', simplified:'懂', pinyin:'dǒng', meaning:'understand', hsk:2, pos:'verb', example:'你懂我的意思吗？', exPinyin:'Nǐ dǒng wǒ de yìsi ma?', exMeaning:'Do you understand what I mean?' },
  { id:'zh_214', simplified:'对', pinyin:'duì', meaning:'correct / right', hsk:2, pos:'adjective', example:'你说的对。', exPinyin:'Nǐ shuō de duì.', exMeaning:'What you said is correct.' },
  { id:'zh_215', simplified:'房间', pinyin:'fángjiān', meaning:'room', hsk:2, pos:'noun', example:'我的房间很小。', exPinyin:'Wǒ de fángjiān hěn xiǎo.', exMeaning:'My room is very small.' },
  { id:'zh_216', simplified:'非常', pinyin:'fēicháng', meaning:'very / extremely', hsk:2, pos:'adverb', example:'这个电影非常好看。', exPinyin:'Zhège diànyǐng fēicháng hǎokàn.', exMeaning:'This movie is extremely good.' },
  { id:'zh_217', simplified:'告诉', pinyin:'gàosu', meaning:'tell / inform', hsk:2, pos:'verb', example:'请告诉我你的名字。', exPinyin:'Qǐng gàosu wǒ nǐ de míngzi.', exMeaning:'Please tell me your name.' },
  { id:'zh_218', simplified:'哥哥', pinyin:'gēge', meaning:'older brother', hsk:2, pos:'noun', example:'我哥哥在上大学。', exPinyin:'Wǒ gēge zài shàng dàxué.', exMeaning:'My older brother is in university.' },
  { id:'zh_219', simplified:'给', pinyin:'gěi', meaning:'give / to / for', hsk:2, pos:'verb', example:'他给我一本书。', exPinyin:'Tā gěi wǒ yī běn shū.', exMeaning:'He gave me a book.' },
  { id:'zh_220', simplified:'贵', pinyin:'guì', meaning:'expensive', hsk:2, pos:'adjective', example:'这双鞋太贵了。', exPinyin:'Zhè shuāng xié tài guì le.', exMeaning:'These shoes are too expensive.' },
  { id:'zh_221', simplified:'孩子', pinyin:'háizi', meaning:'child / children', hsk:2, pos:'noun', example:'她有两个孩子。', exPinyin:'Tā yǒu liǎng gè háizi.', exMeaning:'She has two children.' },
  { id:'zh_222', simplified:'还是', pinyin:'háishì', meaning:'or / still', hsk:2, pos:'conjunction', example:'你喝茶还是喝咖啡？', exPinyin:'Nǐ hē chá háishì hē kāfēi?', exMeaning:'Do you want tea or coffee?' },
  { id:'zh_223', simplified:'黑', pinyin:'hēi', meaning:'black', hsk:2, pos:'adjective', example:'这只猫是黑色的。', exPinyin:'Zhè zhī māo shì hēisè de.', exMeaning:'This cat is black.' },
  { id:'zh_224', simplified:'红', pinyin:'hóng', meaning:'red', hsk:2, pos:'adjective', example:'她穿着一件红衣服。', exPinyin:'Tā chuānzhe yī jiàn hóng yīfu.', exMeaning:'She is wearing a red piece of clothing.' },
  { id:'zh_225', simplified:'可以', pinyin:'kěyǐ', meaning:'can / may / OK', hsk:2, pos:'modal', example:'我可以进来吗？', exPinyin:'Wǒ kěyǐ jìn lái ma?', exMeaning:'May I come in?' },
  { id:'zh_226', simplified:'快', pinyin:'kuài', meaning:'fast / quick', hsk:2, pos:'adjective', example:'你走得太快了！', exPinyin:'Nǐ zǒu de tài kuài le!', exMeaning:'You walk too fast!' },
  { id:'zh_227', simplified:'绿', pinyin:'lǜ', meaning:'green', hsk:2, pos:'adjective', example:'公园里有很多绿树。', exPinyin:'Gōngyuán lǐ yǒu hěn duō lǜ shù.', exMeaning:'There are many green trees in the park.' },
  { id:'zh_228', simplified:'男', pinyin:'nán', meaning:'male / man', hsk:2, pos:'adjective', example:'这里有很多男学生。', exPinyin:'Zhèlǐ yǒu hěn duō nán xuésheng.', exMeaning:'There are many male students here.' },
  { id:'zh_229', simplified:'女', pinyin:'nǚ', meaning:'female / woman', hsk:2, pos:'adjective', example:'她是女医生。', exPinyin:'Tā shì nǚ yīshēng.', exMeaning:'She is a female doctor.' },
  { id:'zh_230', simplified:'手机', pinyin:'shǒujī', meaning:'cell phone / mobile', hsk:2, pos:'noun', example:'我的手机没电了。', exPinyin:'Wǒ de shǒujī méidiàn le.', exMeaning:'My phone is out of battery.' },
  { id:'zh_231', simplified:'时间', pinyin:'shíjiān', meaning:'time', hsk:2, pos:'noun', example:'我没有时间。', exPinyin:'Wǒ méiyǒu shíjiān.', exMeaning:'I don\'t have time.' },
  { id:'zh_232', simplified:'身体', pinyin:'shēntǐ', meaning:'body / health', hsk:2, pos:'noun', example:'他的身体很好。', exPinyin:'Tā de shēntǐ hěn hǎo.', exMeaning:'He is in good health.' },
  { id:'zh_233', simplified:'外', pinyin:'wài', meaning:'outside / foreign', hsk:2, pos:'noun', example:'外面在下雨。', exPinyin:'Wàimiàn zài xià yǔ.', exMeaning:'It is raining outside.' },
  { id:'zh_234', simplified:'玩', pinyin:'wán', meaning:'play / have fun', hsk:2, pos:'verb', example:'孩子们在玩。', exPinyin:'Háizimen zài wán.', exMeaning:'The children are playing.' },
  { id:'zh_235', simplified:'晚上', pinyin:'wǎnshang', meaning:'evening / night', hsk:2, pos:'time', example:'晚上我去跑步。', exPinyin:'Wǎnshang wǒ qù pǎobù.', exMeaning:'I go running in the evening.' },
  { id:'zh_236', simplified:'问题', pinyin:'wèntí', meaning:'question / problem', hsk:2, pos:'noun', example:'你有什么问题？', exPinyin:'Nǐ yǒu shénme wèntí?', exMeaning:'Do you have any questions?' },
  { id:'zh_237', simplified:'新', pinyin:'xīn', meaning:'new', hsk:2, pos:'adjective', example:'我买了一件新衣服。', exPinyin:'Wǒ mǎi le yī jiàn xīn yīfu.', exMeaning:'I bought a new piece of clothing.' },
  { id:'zh_238', simplified:'休息', pinyin:'xiūxi', meaning:'rest / take a break', hsk:2, pos:'verb', example:'工作完了，我需要休息。', exPinyin:'Gōngzuò wán le, wǒ xūyào xiūxi.', exMeaning:'After work, I need to rest.' },
  { id:'zh_239', simplified:'要', pinyin:'yào', meaning:'want / need / will', hsk:2, pos:'modal', example:'我要一杯水。', exPinyin:'Wǒ yào yī bēi shuǐ.', exMeaning:'I want a glass of water.' },
  { id:'zh_240', simplified:'一起', pinyin:'yīqǐ', meaning:'together', hsk:2, pos:'adverb', example:'我们一起去吧！', exPinyin:'Wǒmen yīqǐ qù ba!', exMeaning:"Let's go together!" },
  { id:'zh_241', simplified:'因为', pinyin:'yīnwèi', meaning:'because', hsk:2, pos:'conjunction', example:'我不去，因为下雨了。', exPinyin:'Wǒ bù qù, yīnwèi xià yǔ le.', exMeaning:"I'm not going because it's raining." },
  { id:'zh_242', simplified:'游泳', pinyin:'yóuyǒng', meaning:'swim', hsk:2, pos:'verb', example:'她会游泳。', exPinyin:'Tā huì yóuyǒng.', exMeaning:'She can swim.' },
  { id:'zh_243', simplified:'远', pinyin:'yuǎn', meaning:'far / distant', hsk:2, pos:'adjective', example:'你家离这里远吗？', exPinyin:'Nǐ jiā lí zhèlǐ yuǎn ma?', exMeaning:'Is your home far from here?' },
  { id:'zh_244', simplified:'运动', pinyin:'yùndòng', meaning:'exercise / sport', hsk:2, pos:'noun/verb', example:'我每天运动半个小时。', exPinyin:'Wǒ měitiān yùndòng bàn gè xiǎoshí.', exMeaning:'I exercise for half an hour every day.' },
  { id:'zh_245', simplified:'早上', pinyin:'zǎoshang', meaning:'morning / early morning', hsk:2, pos:'time', example:'早上好！', exPinyin:'Zǎoshang hǎo!', exMeaning:'Good morning!' },
  { id:'zh_246', simplified:'找', pinyin:'zhǎo', meaning:'look for / find', hsk:2, pos:'verb', example:'我在找我的钥匙。', exPinyin:'Wǒ zài zhǎo wǒ de yàoshi.', exMeaning:'I am looking for my keys.' },
  { id:'zh_247', simplified:'知道', pinyin:'zhīdào', meaning:'know (a fact)', hsk:2, pos:'verb', example:'你知道他在哪里吗？', exPinyin:'Nǐ zhīdào tā zài nǎlǐ ma?', exMeaning:'Do you know where he is?' },
  { id:'zh_248', simplified:'最', pinyin:'zuì', meaning:'most / -est', hsk:2, pos:'adverb', example:'这是最好的方法。', exPinyin:'Zhè shì zuì hǎo de fāngfǎ.', exMeaning:'This is the best method.' },
  { id:'zh_249', simplified:'最近', pinyin:'zuìjìn', meaning:'recently / lately', hsk:2, pos:'time', example:'你最近怎么样？', exPinyin:'Nǐ zuìjìn zěnmeyàng?', exMeaning:'How have you been lately?' },
  { id:'zh_250', simplified:'走', pinyin:'zǒu', meaning:'walk / go', hsk:2, pos:'verb', example:'我们走路去吧。', exPinyin:'Wǒmen zǒulù qù ba.', exMeaning:"Let's walk there." },
]

// Shuffle helper for picking distractors
export function getDistractors(wordId: string, count = 3): string[] {
  const others = HSK_WORDS.filter(w => w.id !== wordId)
  const shuffled = [...others].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count).map(w => w.meaning)
}
